---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "ito"
subtitle: "List of all project links"
logo: "assets/logo_black.png"
# Alternatively a fa icon can be provided:
# icon: "fas fa-skull-crossbones"
footer: false #'<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> & <a href="https://github.com/bastienwirtz/homer">homer</a>'  # set false if you want to hide it.header:

# Optional message
#message:
  # url: "https://<my-api-endpoint>" # Can fetch information from an endpoint to override value below.
  #style: "is-info"
  #title: "Contribution!"
  #content: 'You can contribute changes for this page on <a href="https://github.com/ito-org/startpage">Github</a>.'

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "ito"
    icon: "fas fa-code-branch"
    url: "https://github.com/ito-org"
    target: '_blank' # optionnal html a tag target attribute
  - name: "Edit"
    icon: "fab fa-github"
    url: "https://github.com/ito-org/startpage"
    target: '_blank'

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Development"
    icon: "fas fa-code"
    items:
      - name: "GitHub"
        #logo: "/assets/tools/jenkins.png"
        # Alternatively a fa icon can be provided:
        icon: "fab fa-github"
        subtitle: "Link to the GitHub organization"
        tag: "code"
        url: "https://github.com/ito-org"
        target: '_blank' # optional html a tag target attribute
      - name: "Confluence"
        logo: "/assets/tools/confluence.png"
        subtitle: "Documentation and knowledge base"
        tag: "documentation"
        # Optional tagstyle
        url: "http://confluence.ito-app.org"
      - name: "Jira"
        logo: "/assets/tools/jira.png"
        subtitle: "Project Management"
        tag: "organization"
        url: "https://jira.ito-app.org"

  - name: "Communication"
    icon: "fas fa-comments"
    items:
      - name: "Discord"
        icon: "fab fa-discord"
        tag: "communication"
        url: "https://discord.gg/GbSySkC"
      - name: "Q&A Board"
        icon: "fas fa-question"
        subtitle: "documentation"
        url: "https://confluence.ito-app.org/display/IN/questions/all"
      - name: "Mailclient"
        logo: "/assets/tools/freescout.png"
        #icon: "fas fa-question"
        tag: "communication"
        url: "https://helpdesk.ito-app.org"

  - name: "Follow us"
    icon: "fas fa-comments"
    items:
      - name: "Homepage"
        logo: "/assets/logo.png"
        subtitle: "Official web presence of ito"
        tag: "web"
        url: "https://bandemic.app"
      - name: "YouTube"
        subtitle: "YouTube Channel"
        icon: "fab fa-youtube"
        tag: "socialmedia"
        url: "https://www.youtube.com/channel/UCYVYc99hjqv8cBSDvHwFGZQ/featured?view_as=subscriber"
      - name: "Twitter"
        subtitle: "link to the Twitter profile"
        icon: "fab fa-twitter"
        tag: "socialmedia"
        url: "https://twitter.com/BandemicApp?s=20"
      - name: "Instagram"
        icon: "fab fa-instagram"
        #logo: "/assets/tools/elastic.png"
        subtitle: "link to the Instagram profile"
        tag: "socialmedia"
        url: "https://www.instagram.com/bandemic.app"
